# Generated by Django 4.2.13 on 2026-05-25 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingestion', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawActivityRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_FLIGHT', 'Travel Flight'), ('TRAVEL_HOTEL', 'Travel Hotel'), ('TRAVEL_GROUND', 'Travel Ground')], max_length=50)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('parsed_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('parsed_unit', models.CharField(max_length=50)),
                ('normalized_quantity_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('normalized_quantity_kg_co2e', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('activity_date', models.DateField()),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('emission_factor_used', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emission_factor_source', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_from_raw', models.BooleanField(default=False)),
                ('ingestion_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.ingestionjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rows', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_rows', to='authentication.tenant')),
            ],
            options={
                'db_table': 'ingestion_rawactivityrow',
            },
        ),
    ]
