# Generated by Django 4.2.13 on 2026-05-25 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP Fuel'), ('SAP_PROCUREMENT', 'SAP Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_FLIGHT', 'Travel Flight'), ('TRAVEL_HOTEL', 'Travel Hotel'), ('TRAVEL_GROUND', 'Travel Ground')], max_length=50)),
                ('ingestion_mode', models.CharField(choices=[('FILE_UPLOAD', 'File Upload'), ('API_PULL', 'API Pull')], default='FILE_UPLOAD', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_ingested_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='authentication.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('factor_kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(max_length=255)),
                ('valid_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_unit', models.CharField(max_length=50)),
                ('to_unit', models.CharField(max_length=50)),
                ('factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='ingestion_files/')),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='ingestion.datasource')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
